name: ğŸ† Publish Artifact
on:
  workflow_call:
    inputs: {}
jobs:
  build-and-publish:
    runs-on: macos-latest
    steps:
    
      - name: Archive Build
        run: tar czf myPackage.tar.gz .build
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestingArtifact.tar.gz
          path: build.tar.gz
